import type { Role } from "@/types";

export const ROLES: Record<string, Role> = {
  "loup-garou": {
    id: "loup-garou",
    name: "Loup-Garou",
    emoji: "🐺",
    camp: "wolves",
    description: "Chaque nuit, les Loups-Garous se réveillent ensemble et choisissent un villageois à dévorer.",
    power: "Dévorer un villageois chaque nuit",
    objective: "Éliminer tous les villageois pour égaler leur nombre ou les dépasser.",
    colorClass: "bg-red-900",
    borderClass: "border-red-700",
    textClass: "text-red-300",
    nightAction: true,
  },
  voyante: {
    id: "voyante",
    name: "Voyante",
    emoji: "🔮",
    camp: "village",
    description: "Chaque nuit, elle peut découvrir la véritable identité d'un joueur de son choix.",
    power: "Découvrir l'identité d'un joueur chaque nuit",
    objective: "Aider le village à identifier et éliminer tous les Loups-Garous.",
    colorClass: "bg-blue-900",
    borderClass: "border-blue-700",
    textClass: "text-blue-300",
    nightAction: true,
  },
  sorciere: {
    id: "sorciere",
    name: "Sorcière",
    emoji: "🧪",
    camp: "village",
    description: "Possède deux potions qu'elle peut utiliser une seule fois chacune durant la partie.",
    power: "Potion de Vie et Potion de Mort (une fois chacune)",
    objective: "Protéger le village et éliminer les Loups-Garous.",
    colorClass: "bg-green-900",
    borderClass: "border-green-700",
    textClass: "text-green-300",
    nightAction: true,
  },
  chasseur: {
    id: "chasseur",
    name: "Chasseur",
    emoji: "🏹",
    camp: "village",
    description: "Lorsqu'il meurt, il peut immédiatement désigner un joueur qui mourra avec lui.",
    power: "Dernier souffle : tuer un joueur lors de sa mort",
    objective: "Utiliser sa mort pour éliminer un Loup-Garou suspecté.",
    colorClass: "bg-yellow-900",
    borderClass: "border-yellow-700",
    textClass: "text-yellow-300",
  },
  cupidon: {
    id: "cupidon",
    name: "Cupidon",
    emoji: "💘",
    camp: "neutral",
    description: "La première nuit uniquement, il désigne deux joueurs qui deviennent 'Amoureux'.",
    power: "Créer un couple d'amoureux (première nuit uniquement)",
    objective: "Survie des Amoureux (si Cupidon est Amoureux, sinon objectif du village).",
    colorClass: "bg-pink-900",
    borderClass: "border-pink-700",
    textClass: "text-pink-300",
    nightAction: true,
    firstNightOnly: true,
  },
  "petite-fille": {
    id: "petite-fille",
    name: "Petite Fille",
    emoji: "👧",
    camp: "village",
    description: "Peut espionner discrètement les Loups-Garous la nuit en entrouvrant les yeux.",
    power: "Espionner les Loups-Garous (risque de mort si découverte)",
    objective: "Identifier les Loups-Garous sans se faire découvrir.",
    colorClass: "bg-purple-900",
    borderClass: "border-purple-700",
    textClass: "text-purple-300",
  },
  voleur: {
    id: "voleur",
    name: "Voleur",
    emoji: "🎭",
    camp: "neutral",
    description: "La première nuit, il peut échanger sa carte avec l'une des deux cartes non distribuées.",
    power: "Échanger de rôle (première nuit uniquement)",
    objective: "Celui du rôle qu'il adopte.",
    colorClass: "bg-orange-900",
    borderClass: "border-orange-700",
    textClass: "text-orange-300",
    nightAction: true,
    firstNightOnly: true,
  },
  "simple-villageois": {
    id: "simple-villageois",
    name: "Simple Villageois",
    emoji: "👨‍🌾",
    camp: "village",
    description: "Aucun pouvoir spécial, mais peut voter et participer aux débats du village.",
    objective: "Identifier et éliminer tous les Loups-Garous par le vote.",
    colorClass: "bg-gray-700",
    borderClass: "border-gray-600",
    textClass: "text-gray-300",
  },
};

export const ROLES_ARRAY = Object.values(ROLES);

export const NIGHT_ORDER = [
  "voleur",
  "cupidon", 
  "voyante",
  "loup-garou",
  "sorciere"
];

export const CAMPS = {
  village: {
    name: "Village",
    color: "text-green-400",
    bgColor: "bg-green-900",
  },
  wolves: {
    name: "Loups-Garous", 
    color: "text-red-400",
    bgColor: "bg-red-900",
  },
  neutral: {
    name: "Neutre",
    color: "text-yellow-400",
    bgColor: "bg-yellow-900",
  },
};
